### PR TITLE
ssl verify should not be disabled while making requests

### PR DESCRIPTION
**Pull request by rhyw**
There's security warning prompts with verify disabled.

### CODE REVIEW

**Comment by hanchuntao** [comment]
I test it before, if set ssl, it will display error, the code can not run, maybe need to add some certification

**Comment by rhyw** [comment]
> I test it before, if set ssl, it will display error, the code can not run, maybe need to add some certification

In that case, should find some way to pass in the cert. I'll take a look.

**Comment by rhyw** [comment]
Latest patch explicitly specify cert by getting from environment variable. My local test doesnt yield any issues.

**Comment by hanchuntao** [comment]
OK, please update the commit

**Pull request merged**
