### PR TITLE
Clean up download module

### PR DESCRIPTION
**Pull request by rhyw**

### CODE REVIEW

**Comment by rhyw** [comment]
It confuses me to have both a `BrewBuild` and a `BrewConnector` in two different modules while both are keep growing over time. I think they're pretty similar and could definitely be merged into one.

@hanchuntao any special reason a separate `download.py` is really needed?

**Comment by hanchuntao** [comment]
>

**Comment by hanchuntao** [comment]
Yes, `download.py` is used to download archives from brew for our original design, but then we add more functions about brew operation in `kojiconnector.py`.  We can combine them, or move download functions in `kojiconnector.py` to `download.py`.

**Comment by huiwangredhat** [comment]
LGTM.

**Pull request merged**
