### PR TITLE
Create symlink for the corgi ssl cert verification

### PR DESCRIPTION
**Pull request by huiwangredhat**
Fix the SSL CERTIFICATE_VERIFY_FAILED for connection with corgi

### CODE REVIEW

**Comment by huiwangredhat** [comment]
This will try to fix the error: _httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)_
The reference: shorturl.at/ahqUX

**Comment by rhyw** [comment]
@huiwangredhat It looks like it's caused by changes in https://github.com/RedHatProductSecurity/openlcs/pull/19 .

Have you verified if this change helps?  I'll also take a close look on httpx documentation and see if this could be fixed via other means..

**Comment by huiwangredhat** [comment]
@rhyw, I verified the fix locally, and it works.

**Comment by huiwangredhat** [comment]
@rhyw, Humm, it hasn't passed the pipeline test. Let me test it to build a container locally first.

**Comment by rhyw** [comment]
@huiwangredhat I think https://github.com/RedHatProductSecurity/openlcs/pull/51 should resolve the issue here.

**Comment by huiwangredhat** [comment]
@rhyw thanks for your reply and fix. Let's close this PR and use [#51](https://github.com/RedHatProductSecurity/openlcs/pull/51)

**Pull request closed without merging**
